apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-certificate
  namespace: default
spec:
  dnsNames:
    - www.bohdan-microservice-challenge.xyz
    - bohdan-microservice-challenge.xyz
  secretName: letsencrypt-prod-certificate-tls
  commonName: bohdan-microservice-challenge.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
