apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: analytics-client-client
spec:
  commonName: analytics-client-client
  secretName: analytics-client-client
  issuerRef:
    name: ingress-issuer
  usages:
  - "client auth"
  - "signing"
  - "key encipherment"
  duration: 17520h # 2 years
  renewBefore: 48h